package com.github.twostone.leaderboard.ui.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g class LoginView
 * extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CreateCompetitionDesign extends CssLayout {
  protected FormLayout createForm;
  protected Label emailHeaderLabel;
  protected TextField nameField;
  protected Label dateLabel;
  protected DateField dateField;
  protected Button submitButton;
  protected Button abortButton;

  public CreateCompetitionDesign() {
    Design.read(this);
  }
}
