language: java
jdk:
- oraclejdk8
script:
- ./gradlew check
- ./gradlew assembleDist installDist

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: openshift
  skip_cleanup: true
  user: walter.niklas@gmail.com
  password:
    secure: tyqf6RcuIJ3JcKxavivxni/ZIdQBZTa2MEHOiHr6GsQHmW56Hoba32OPI/WgQDn4vua1femsWbaH8u4j7HiwSjrW+mAVjah+eSv+WxxMzR+HAAHVreRB7JHiUaTlaW7rip3sCjkh5Wh/rANsrexUgVOmtz5NYp8Qa+JOF1Z3NJvkgo+TeK90GWnXqqslpUjAY/Blbqx1FoLMfUUmFulsJzRc63cNzvjaJ/JQexX0cge16TRH5nogygKGxg8Q3i7+L40soilOFcfow3q5xkNefHf5v9LBnNlEyYBWF9bou5B6sGdTud6NME2rGzmInBC03Atx0ldguFU/yZ8mwQh1gxR+6tYp+XIw9lMke3I5AJqhQ+INP6Xop7S5rVLo63f2ja5kTQAgcxoJ8Dca/0Z6M+H0MhJ+tu/BaH3tnWOykcwqgIki5tDRXtVB4Qa7EPf7r+JfNoipF1O0Ib9JrB62uQGhQwBxfFhQouX1jEmqVEK13Rb/q2x4FpFlTuIFvoVDyvaEX4wgAZoaw9KOnAYs5JNRshAVd0hKDG3pBptgm/3I0O6hIt2zOeuSXC9nhIBsKPGGOXWI+ljKVNSSYZKG559YQknyaXZQy58EjfGMNYSZnikkw64qM/KCwu4DSSvRcDjwuiQNIvnc/EInW/mqJlRw21x+TFKOvtsni6ghJ2k=
  app: leaderboard
  domain: mcripper
  on:
    repo: TwoStone/leaderboard
