spring:
  application:
    name: Leaderboard

server:
  port: 8080
    
---

spring:
  profiles: prod
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
logging:
  path: ./logs    
